### ISSUE TITLE
Can you update vuetify to 1.1? 

### ISSUE THREAD

**Issue by rajagopalx** [nasirouwagana/vuebase#2]
Vuetify 1.1 version is released. Can you please update vuebase to vuetify 1.1?

**Comment by nasirouwagana** [comment]
Hello @rajagopalx I am working on that. It will be available very soon.

**Comment by rajagopalx** [comment]
Thanks @nasirouwagana

**Comment by zodchiy** [comment]
How about vuetify 1.2?

**Comment by nasirouwagana** [comment]
@zodchiy @rajagopalx, I just updated Vuebase project to vuetify 1.2 and Vue CLI 3.

**Comment by rajagopalx** [comment]
Thanks a lot
